package buildSrc.src.main.kotlin

private object Versions {
    const val androidxCoreVersion = "1.10.1"
    const val appcompatVersion = "1.6.1"
    const val lifecycleViewModelKtxVersion = "2.6.1"
    const val materialVersion = "1.9.0"
    const val composeVersion = "1.4.3"
    const val lifecycleVersion = "2.6.1"
    const val activityComposeVersion = "1.7.2"
    const val androidJUnitVersion = "1.1.5"
    const val espressoCoreVersion = "3.5.1"
    const val navigationComposeVersion = "2.6.0"
    const val materialIconsExtendedVersion = "1.4.3"
    const val roomRuntimeVersion = "2.5.1"
    const val kotlinxCoroutinesAndroidVersion = "1.6.4"
    const val gsonVersion = "2.9.0"
    const val materialDialogsVersion = "0.8.1-rc"
    const val hiltAndroidVersion = "2.44"
    const val hiltNavigationComposeVersion = "1.0.0"
    const val material3Version = "1.1.0"
    const val kotestVersion = "5.5.5"
    const val mockkVersion = "1.13.4"
}

object Libs {
    const val androidxCore = "androidx.core:core-ktx:${Versions.androidxCoreVersion}"
    const val appcompat = "androidx.appcompat:appcompat:${Versions.appcompatVersion}"
    const val lifecycleViewModelKtx = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecycleViewModelKtxVersion}"
    const val material = "com.google.android.material:material:${Versions.materialVersion}"
    const val composeUi = "androidx.compose.ui:ui:${Versions.composeVersion}"
    const val composeMaterial = "androidx.compose.material:material:${Versions.composeVersion}"
    const val composeUiToolingPreview = "androidx.compose.ui:ui-tooling-preview:${Versions.composeVersion}"
    const val lifecycleRuntimeKtx = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.lifecycleVersion}"
    const val activityCompose = "androidx.activity:activity-compose:${Versions.activityComposeVersion}"
    const val androidTestJUnit = "androidx.test.ext:junit:${Versions.androidJUnitVersion}"
    const val espressoCore = "androidx.test.espresso:espresso-core:${Versions.espressoCoreVersion}"
    const val composeUiTestJUnit4 = "androidx.compose.ui:ui-test-junit4:${Versions.composeVersion}"
    const val composeUiTooling = "androidx.compose.ui:ui-tooling:${Versions.composeVersion}"
    const val navigationCompose = "androidx.navigation:navigation-compose:${Versions.navigationComposeVersion}"
    const val materialIconsExtended = "androidx.compose.material:material-icons-extended:${Versions.materialIconsExtendedVersion}"
    const val roomRuntime = "androidx.room:room-runtime:${Versions.roomRuntimeVersion}"
    const val roomCompiler = "androidx.room:room-compiler:${Versions.roomRuntimeVersion}"
    const val roomKtx = "androidx.room:room-ktx:${Versions.roomRuntimeVersion}"
    const val kotlinxCoroutinesAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.kotlinxCoroutinesAndroidVersion}"
    const val gson = "com.google.code.gson:gson:${Versions.gsonVersion}"
    const val materialDialogs = "io.github.vanpra.compose-material-dialogs:datetime:${Versions.materialDialogsVersion}"
    const val hiltAndroid = "com.google.dagger:hilt-android:${Versions.hiltAndroidVersion}"
    const val hiltAndroidCompiler = "com.google.dagger:hilt-android-compiler:${Versions.hiltAndroidVersion}"
    const val hiltNavigationCompose = "androidx.hilt:hilt-navigation-compose:${Versions.hiltNavigationComposeVersion}"
    const val material3 = "androidx.compose.material3:material3:${Versions.material3Version}"
    const val material3WindowSizeClass = "androidx.compose.material3:material3-window-size-class:${Versions.material3Version}"
    const val kotestRunnerJUnit5 = "io.kotest:kotest-runner-junit5:${Versions.kotestVersion}"
    const val kotestAssertionsCore = "io.kotest:kotest-assertions-core:${Versions.kotestVersion}"
    const val kotestProperty = "io.kotest:kotest-property:${Versions.kotestVersion}"
    const val mockk = "io.mockk:mockk:${Versions.mockkVersion}"
}
